// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalksAPIs.Data;

#nullable disable

namespace NZWalksAPIs.Migrations
{
    [DbContext(typeof(NZWalkDBContext))]
    partial class NZWalkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalksAPIs.Model.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d914a9a-eb9a-43ce-8193-30c55d1ac8ac"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("614ffc6f-81f6-4d1d-bc99-58aff329f3b1"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("e89da2b2-3be3-4761-8d90-00371b8ca5b8"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalksAPIs.Model.Domain.Regions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regionspoperties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d914a9a-eb9a-43ce-8193-30c55d1ac8ac"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Auckland_skyline_from_Mt_Eden.jpg/2560px-Auckland_skyline_from_Mt_Eden.jpg"
                        },
                        new
                        {
                            Id = new Guid("614ffc6f-81f6-4d1d-bc99-58aff329f3b1"),
                            Code = "WLG",
                            Name = "Wellington",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Wellington_City.jpg/2560px-Wellington_City.jpg"
                        },
                        new
                        {
                            Id = new Guid("e89da2b2-3be3-4761-8d90-00371b8ca5b8"),
                            Code = "CHC",
                            Name = "Christchurch",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Christchurch_Cathedral_Square.jpg/2560px-Christchurch_Cathedral_Square.jpg"
                        });
                });

            modelBuilder.Entity("NZWalksAPIs.Model.Domain.Walks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LenghtInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("WalksProperties");
                });

            modelBuilder.Entity("NZWalksAPIs.Model.Domain.Walks", b =>
                {
                    b.HasOne("NZWalksAPIs.Model.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalksAPIs.Model.Domain.Regions", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
